language: python
cache: pip

python:
  - "3.6"
  - "2.7"

matrix:
  - python: "2.7"
    script: make testpy2
  - python: "3.6"
    script: make test
    after_success: python3 -m codecov --token 2b1a0cc9-52e4-4942-8816-8554a1f5d0f1

install:
    - python2.7 -m pip install -r requirements.txt
    - python3.7 -m pip install -r requirements.txt
    - python3.7 -m pip install codecov

branches:
  only:
  - master

notifications:
  email: false
