language: python
cache: pip

python:
  - "3.6"

git:
    submodules: false

install:
    - pip install -r requirements.txt
    # - pip install coveralls
    - pip install codecov

script: make test

after_success:
    # - codecov --token f8f2787b-4aa9-4161-8b13-88ddde282d57
    # - coveralls

branches:
  only:
  - master

notifications:
  email: false
