language: python
cache: pip

python:
  - "3.6"

git:
    submodules: false

install:
    - pip install -r requirements.txt
    - pip install codecov

script: make test

after_success:
    - codecov --token 2b1a0cc9-52e4-4942-8816-8554a1f5d0f1

branches:
  only:
  - master

notifications:
  email: false
