language: python
cache: pip

matrix:
  - python: "2.7"
    env: PYTHONVER=2
  - python: "3.6"
    env: PYTHONVER=3
    after_success: python3 -m codecov --token 2b1a0cc9-52e4-4942-8816-8554a1f5d0f1

branches:
  only:
  - master

install: 
  - if [ "$PYTHONVER" = "2" ]; then python2 -m pip install -r requirements.txt; fi
  - if [ "$PYTHONVER" = "3" ]; then python3 -m pip install -r requirements.txt && python3 -m pip install codecov; fi

script: 
  - if [ "$PYTHONVER" = "2" ]; then echo "Python2" && make testpy2; fi
  - if [ "$PYTHONVER" = "3" ]; then echo "Python3" && make test; fi
  - echo $PYTHONVER

notifications:
  email: false
