dist: xenial
language: python
cache: pip

matrix:
  include:
    - python: "3.7"
      env: PYTHONVER=3

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - graphviz
  homebrew:
    update: true
    packages:
      - python
      - graphviz
      - python2

branches:
  only:
  - master

install: 
  - python3 -m pip install -r requirements.txt && python3 -m pip install -e .[dev]

script: 
  - echo "Python3" && make test

after_success: 
  - python3 -m codecov --token 2b1a0cc9-52e4-4942-8816-8554a1f5d0f1

notifications:
  email: false
