version: '2'
services:
  # zookeeper:
  #   image: timkpaine/zookeeper:latest # wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: timkpaine/kafka:latest # wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_CREATE_TOPICS: "tributary:1:1"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sockf

  echo-server:
    image: timkpaine/echo-server:latest # jmalloc/echo-server
    ports:
      - 12345:8080

  # socketio-server:
  #   image: timkpaine/docker-socketio:latest # voduytuan/docker-socketio
  #   ports:
  #     - 8069:8069
  #   volumes:
  #     - ./scripts/server.js:/srv/app.js

  # postgres:
  #     image: timkpaine/postgres:latest # postgres
  #     environment:
  #         - POSTGRES_PASSWORD=test
  #     volumes:
  #         - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     ports:
  #         - "5432:5432"

  # redis:
  #   image: timkpaine/redis:latest # redis
  #   ports:
  #     - "6379:6379"
